
[origins]

	[origins."tinkerer:tallest"]
		"tinkerer:tallest" = true
		enabled = true

	[origins."tinkerer:taller"]
		"tinkerer:taller" = true
		enabled = true

	[origins."tinkerer:semishort"]
		"tinkerer:semishort" = true
		enabled = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."tinkerer:demistout"]
		"tinkerer:demistout" = true
		enabled = true

	[origins."tinkerer:lanky"]
		"tinkerer:lanky" = true
		enabled = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."tinkerer:demishort"]
		enabled = true
		"tinkerer:demishort" = true

	[origins."tinkerer:impish"]
		"tinkerer:impish" = true
		enabled = true

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."tinkerer:oversize1"]
		"tinkerer:oversize1" = true
		enabled = true

	[origins."tinkerer:orcish"]
		"tinkerer:orcish" = true
		enabled = true

	[origins."tinkerer:oversize2"]
		"tinkerer:oversize2" = true
		enabled = true

	[origins."tinkerer:stout"]
		"tinkerer:stout" = true
		enabled = true

	[origins."tinkerer:demilanky"]
		"tinkerer:demilanky" = true
		enabled = true

	[origins."tinkerer:tall"]
		"tinkerer:tall" = true
		enabled = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."tinkerer:sized"]
		"tinkerer:sized" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."tinkerer:demitall"]
		"tinkerer:demitall" = true
		enabled = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."tinkerer:unaffected"]
		enabled = true

	[origins."tinkerer:short"]
		"tinkerer:short" = true
		enabled = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."tinkerer:oversize3"]
		enabled = true
		"tinkerer:oversize3" = true

	[origins."tinkerer:hemidemishort"]
		enabled = true
		"tinkerer:hemidemishort" = true

